version: "3.9"
services:
  api:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "pip install -r requirements.txt && uvicorn backend.api:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "pip install -r requirements.txt && celery -A backend.tasks.celery_app worker --loglevel=info"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
